<?php
//generated by kissgo,don't edit this file manually!
defined ( 'KISSGO' ) or exit ( 'No direct script access allowed' );
$settings = KissGoSetting::getSetting ();

$settings ['DEBUG'] = 2;

$settings ['CLEAN_URL'] = true;

$settings ['I18N_ENABLED'] = false;

$settings ['GZIP_ENABLED'] = true;

$settings ['TIMEZONE'] = 'Asia/Shanghai';

$settings ['SECURITY_KEY'] = '*wx5b9JqLUD(sq(y0-HhVs1t@nP=wrIvNL0utjR2gZXXR#GI';

$settings ['date_format'] = 'Y-m-d';

$settings ['site_name'] = '我的网站';

$settings ['database'] = array ('default' => array ('driver' => 'MySQL', 'encoding' => 'UTF8', 'host' => 'localhost', 'port' => '3306', 'prefix' => '', 'user' => 'root', 'password' => '888888', 'dbname' => 'kissgodb' ),'postgres'=>array ('driver' => 'PostgreSQL', 'encoding' => 'UTF8', 'host' => '10.243.118.141', 'prefix' => '', 'user' => 'ngf', 'password' => '888888', 'dbname' => 'test' ) );

$settings ['THEME'] = 'default';

# $settings ['BASE_URL'] = 'http://ndev1.covidien.com/autol';

$settings ['link_types'] = 'a';

$settings ['site_keywords'] = 'asdfasdfasdf';

$settings ['site_desc'] = 'asdf asd asdf ';

$settings ['site_copyright'] = 'asdfasdf';

$settings ['site_beian'] = 'asdfasdfasdf ';

// end of D:\www\kissgo\appdata\settings.php
?>